### ISSUE TITLE
Not working with react-native version 38

### ISSUE THREAD

**Issue by dushyantdigital** [pixelfactoryio/react-native-pixfactory-accordion#1]
I used it on version 32 and was working perfect. but when i updated my RN its not working anymore. No error message.

**Comment by amine7536** [comment]
Hi, thanks for reporting the issue. 

This component is based on **react-native-collapsible**, which is not working since version 36 of ReactNative : https://github.com/oblador/react-native-collapsible/issues/51

The issue seems related to a braking change in the native implementation introduced in RN 36. According the issue thread a fix will be available in future RN updates, probably RN 40. https://github.com/facebook/yoga/commit/204aba80b9818db0e9b6f6f74d9a2fd2580ede1c

Rgds
Amine
